### PR TITLE
[WIP] Module/Week 2

### PR DESCRIPTION
**Pull request by adrianmcli**
More WIP. This one takes a bit of work since we need to thin out the SNARK stuff (particularly pinnochio) but also add in some STARK stuff. Nothing that can't be done, but just takes time.

### Practical

- [ ] Circom Crash Course (build from command line; ZKU course)
- [ ] Write a circuit for a token mixer

### Study

- [x] KZG Polynomial Commitments (keep this simple and black-boxed)
- [ ] Trusted Setups (keep this simple and black-boxed; reference Inevitable Ethereum)
- [ ] SNARKs and STARKs
- [ ] SNARKs
   - [ ] From Computation to ZKPs (use only Vitalik's blog post; arithmetic circuits, R1CS, QAP)
   - [ ] Groth16 (keep this simple and black-boxed)
- [ ] STARKs (follow Vitalik's blog posts)

### CODE REVIEW

**Comment by NOOMA-42** [comment]
note: looking into snark course by comm team

**Comment by adrianmcli** [comment]
> note: looking into snark course by comm team

Can you throw the link here?

**Comment by adrianmcli** [comment]
@NOOMA-42 any update?

**Comment by adrianmcli** [comment]
We'll definitely need to redo this one, but I want to merge this first as I am going to change up the format of the repo a bit (i.e. modules -> week).

**Pull request merged**
