### PR TITLE
Module 0 (pre-requisite module)

### LINKED ISSUE #26: Week Zero
### Summary

[Week Zero](https://github.com/privacy-scaling-explorations/core-program/issues/24)
Course Info
 About This Course
 Open-Source Culture, Git, and Github
 How to ask questions, where to find help
 How to submit your assignments (PR workflow)
 Course FAQ
Knowledge
 A Primer for ZKPs
 Thought Experiments
 Use-Cases and Applications
 Supplemental materials on ZKPs [optional]
 Number Theory

### Location

- Module Name:
- Section/Step:

### Proposed Correction

If you have a suggestion for how to fix the issue, please include it here.

### Screenshots (if applicable)

Attach any screenshots that might help explain the issue.

### Additional Context

Add any other information that might be helpful, such as links to related tutorials or explanations.

### PR DESCRIPTION
**Pull request by adrianmcli**
Fixes #26 

This is currently a WIP PR. Still need to fill in some of the new sections.

Note that I created a 2024 folder so that we can do merge to main without worrying about disturbing the existing structure. Once everything is done, we can replace the main documents with everything from the 2024 folder.

### Course Info
- [x] About This Course
- [x] Open-Source Culture, Git, and Github
- [x] How to ask questions, where to find help

### Knowledge
- [x] A Primer for ZKPs
- [x] Thought Experiments
- [x] Use-Cases and Applications
- [x] Supplemental materials on ZKPs [optional]
- [x] Number Theory

### CODE REVIEW

**Comment by NOOMA-42** [comment]
LGTM

**Comment by mojalil** [comment]
Thoughts on  "How to ask questions" & "Where to ask questions"

Currently, the forums to ask questions are either Discord or Telegram. While these are great for real-time conversations, I don't think they are ideal for information retrieval.

Questions and answers can get buried in chat history. So I was thinking it might be better if we encourage students to post their questions as issues on github ?

What do you guys think?

I'd also add it might be worth giving them an example of what that could look like.

**Comment by adrianmcli** [comment]
@mojalil I think maybe we should create an issue label and have them use it. Otherwise it can be a bit overwhelming. But I think that's a good idea for getting them used to using GitHub!

We can even make an issue template for them. But I'd want to keep it minimal because I want to train them to think about how to write a good issue.

**Comment by mojalil** [comment]
@adrianmcli I would

**Comment by adrianmcli** [comment]
@mojalil I am going to merge this first. Please make an issue and PR if you want to improve this further later on.

**Pull request merged**
